

server:
  port: 8044

sitehoster:
  tempDir: target/tempdir
  sites:
#    - name: s1
#      git-source:
#        uri: https://github.com/e-codex/ecodex.git
#        branches: gh-pages
#        default-ref: refs/remotes/origin/gh-pages

    - name: s4
      git-source:
        uri: ssh://git@git.brz.gv.at:7999/jeumv/eumv_eugw_interface_site.git
        branches: master
        default-ref: refs/remotes/origin/master
        private-key-file: file://C:/Users/spindlest/.ssh/test2key_rsa
        privateKeyPassphrase: ""

logging:
  level:
    at:
      stsp:
        dev: DEBUG
    org:
      eclipse:
        jgit: TRACE

